name: Build Electron Installer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the Next.js app
      - name: Build Next.js
        run: npm run build

      # Package the Electron app and create an installer
      - name: Create Installer
        run: npm run make-installer

      # Upload the installer artifact
      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: ArchivalDeepDive-installer
          path: dist/
