name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use a version compatible with your project

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build Next.js app
      - name: Build Next.js App
        run: npm run build

      # Package Electron app
      - name: Install Electron Packager
        run: npm install electron-packager --save-dev

      - name: Package Electron App
        run: npx electron-packager . MyApp --platform=win32 --arch=x64 --out=dist --overwrite

      # Upload `.exe` as a build artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-windows
          path: dist/MyApp-win32-x64/
